# Generated by Django 2.2.16 on 2022-06-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220615_2028'),
        ('review', '0002_auto_20220615_1331'),
    ]

    operations = [
    ]
