# Generated by Django 2.2.16 on 2022-06-15 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_merge_20220615_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Укажите логин', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Использовать имя meзапрещено.', regex='^[mM][eE]$')], verbose_name='Логин'),
        ),
    ]
